### PR TITLE
[Feature/PE1-22] Add design files for home page

### PR DESCRIPTION
**Pull request by JaedonC**
Code a basic home page for Poly Events, which includes a create event button, the organization name, a display of active events.

### CODE REVIEW

**Review by Sheldonsu28 — COMMENTED** [review]
Does this merge only includes pictures?

**Comment by JaedonC** [comment]
> Does this merge only includes pictures?

Yes

**Review by Sheldonsu28 — APPROVED** [review]

**Review by jimmy-lan — CHANGES_REQUESTED** [review]
Hi Jaedon,

Congratulations on submitting your first pull request!

Sorry for not explaining this clearly. There is a difference between pull requests and Jira tickets. In a pull request, you create some changes and propose the changes. In Jira, you create tickets to work on or assign tasks to others.

In a pull request, we want to describe the purpose of our changes clearly. This pull request doesn't seem to contain any code changes. Therefore, we would prefer a name such as **Add design files for home page**. Do you mind updating that title and the branch name (you might have to close this PR, delete the branch, then open a new one)?

Also, since the ticket **PE1-22** does not seem to be assigned to some developers, would you mind changing the title of that ticket to something like **Add design files for home page** as well?

I think it might be a good idea for us to have a dedicated folder for design files, rather than adding them all into the root folder. I just messaged on Slack and created several tickets for us to ramp you up in using terminal git. Please see below:

* https://polyteam.atlassian.net/browse/PE1-25
* https://polyteam.atlassian.net/browse/PE1-26

We added some help for you in terms of terminal git in the next internal meeting (tomorrow morning at 9 AM). Sorry for the confusion and thanks for your contributions!

**Comment by JaedonC** [comment]
I have closed the PR and deleted the branch and will wait for a dedicated design file folder before opening another PR and reuploading the files.

Sorry for all the confusion and thanks for the help!

**Pull request closed without merging**
